Repository nxt-dev/nxt, pull requests merged in 2021-02, with the labels that each got.

#68 Fix for cli execution in a context with no parameters
  nxt/remote/server.py
Labels: bug

#69 Comp Speed Improvement
  nxt/nxt_layer.py
  nxt/nxt_path.py
  nxt/stage.py
Labels: backend

#72 Another Comp Patch
  nxt/nxt_layer.py
  nxt/stage.py
  nxt/test/StageInstanceTest_Layer0.nxt
  nxt/test/StageInstanceTest_Layer1.nxt
  nxt/test/test_stage.py
Labels: backend, bug

#74 Comp imporvements and patches
  nxt/nxt_layer.py
  nxt/stage.py
Labels: backend, bug
